import { timingSafeEqual } from "node:crypto";

/**
 * Minimum length we accept for ADMIN_TOKEN. 24 base64url chars ≈ 144 bits of
 * entropy if generated by `crypto.randomBytes(24).toString("base64url")` —
 * which is what `.env.local.example` recommends.
 */
const MIN_TOKEN_LENGTH = 24;

/**
 * Constant-time check of a user-supplied admin token against ADMIN_TOKEN.
 * Returns false if:
 *   - the env var is unset
 *   - the env var is shorter than MIN_TOKEN_LENGTH (refuses weak tokens
 *     instead of silently allowing them)
 *   - the supplied token is missing, the wrong length, or doesn't match
 */
export function adminTokenMatches(provided: string | null | undefined): boolean {
  const expected = process.env.ADMIN_TOKEN;
  if (!expected || expected.length < MIN_TOKEN_LENGTH) return false;
  if (!provided) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}
